version: "3"

services:

  mongodb:
    container_name: mongodb
    image: mongo:5.0
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=dbPassword
    ports:
      - 37017:27017
    volumes:
      - db:/data/db

  # master-data:
  #   container_name: master-data
  #   depends_on:
  #     - mongodb
  #   build: ./master-data
  #   restart: unless-stopped
  #   ports:
  #     - 9000:9000
  #   env_file: ./master-data/.env
  #   stdin_open: true
  #   tty: true
  #   volumes:
  #     - ./master-data:/usr/app/master-data

  # brand-management:
  #   container_name: brand-management
  #   depends_on:
  #     - mongodb
  #   build: ./brand-management
  #   restart: always
  #   ports:
  #     - 9001:9001
  #   env_file: ./brand-management/.env
  #   volumes:
  #     - ./brand-management:/usr/app/brand-management

  campaign-managemet:
    container_name: campaign-management
    depends_on:
      - mongodb
    build: ./campaign-management
    restart: unless-stopped
    ports:
      - 9002:9002
    volumes:
      - ./campaign-management:/usr/app/campaign-management
      - ./campaign-management/deploy-ext/php/local.ini:/usr/local/etc/php/conf.d/local.ini

  webserver-nginx:
    image: nginx:alpine
    container_name: webserver-nginx
    restart: unless-stopped
    tty: true
    ports:
        - "80:80"
        - "443:443"
    volumes:
        - ./:/var/www
        - ./deploy-ext/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
        - app-network
    depends_on:
        - app

volumes:
  db: